apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cilium
    #    role: db
    tier: backend
  annotations:
    kubernetes.io/change-cause: "Deploying Mongo 4.2 Version"
  name: mongo
  namespace: cilium-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium
      #  role: db
      tier: backend
  template:
    metadata:
      labels:
        app: cilium
        # role: db
        tier: backend
    spec:
      containers:
      - name: db
        image: mongo:4.2
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cilium
    #    role: svc
    tier: backend
  name: mongo-svc
  namespace: cilium-testing
spec:
  type: ClusterIP
  selector:
    app: cilium
    # role: svc
    tier: backend
  ports:
  - port: 27017
    targetPort: 27017
