apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cilium
    #    role: web
    tier: frontend
  annotations:
    kubernetes.io/change-cause: "Deploying PHP WEB V5"
  name: php
  namespace: cilium-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium
      #      role: web
      tier: frontend
  template:
    metadata:
      labels:
        app: cilium
        # role: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: gcr.io/google_samples/gb-frontend:v5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cilium
    #  role: svc
    tier: frontend
  name: php-svc
  namespace: cilium-testing
spec:
  type: NodePort
  selector:
    app: cilium
    # role: web
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32323
